-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(SALES_AMOUNT)*P.PRICE AS SALES
FROM PRODUCT P
INNER JOIN OFFLINE_SALE F ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE