-- 코드를 작성해주세요
SELECT H.EMP_NO, H.EMP_NAME, 
(CASE WHEN AVG(G.SCORE) >= 96 THEN 'S'
      WHEN AVG(G.SCORE) >= 90 THEN 'A'
      WHEN AVG(G.SCORE) >= 80 THEN 'B'
      ELSE 'C' END) AS GRADE, 
(CASE WHEN AVG(G.SCORE) >= 96 THEN (H.SAL)*0.2
      WHEN AVG(G.SCORE) >= 90 THEN (H.SAL)*0.15
      WHEN AVG(G.SCORE) >= 80 THEN (H.SAL)*0.1
      ELSE 0 END) AS BONUS
FROM HR_EMPLOYEES H
JOIN HR_GRADE G ON H.EMP_NO = G.EMP_NO
GROUP BY H.EMP_NO
ORDER BY H.EMP_NO

