SELECT
  B.TITLE,
  B.BOARD_ID,
  R.REPLY_ID,
  R.WRITER_ID,
  R.CONTENTS,
  DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R
  ON R.BOARD_ID = B.BOARD_ID
WHERE B.CREATED_DATE >= '2022-10-01'
  AND B.CREATED_DATE <  '2022-11-01'   -- 게시글이 2022-10에 작성된 것만
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;  -- 정렬은 댓글 작성일 → 제목
